title: Your awesome title
author: Untung Tanujaya
email: utanujaya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about work

# social links
twitter_username: untungtanujaya
github_username:  untungtanujaya

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
